services:
  - docker

before_install:
  - docker pull openroberta/it:11

script:
  - docker run --detach --name openroberta --entrypoint "/opt/runIT.sh" openroberta/it:11 ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} 3.8.3
  - docker logs --follow openroberta

after_success:
  - docker commit openroberta openroberta-built
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --detach --name openroberta-built $ci_env --entrypoint "/bin/bash" openroberta-built -c "cd openroberta-lab && bash <(curl -s https://codecov.io/bash)"
  - docker logs --follow openroberta-built

notifications:
  irc: "chat.freenode.net#open-roberta"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9656874f95990cb84024
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
